### PR TITLE
m_sentPackets sequence fix & some other minor changes

### PR DESCRIPTION
**Pull request by jorgenpt**
- Fix the assert that triggers if you only intermittently send reliable messages
- Clean up the `acked` field which isn't being used

### CODE REVIEW

**Comment by jorgenpt** [comment]
Not sure why this is failing on macOS, I'll investigate.

**Comment by jorgenpt** [comment]
Huh. It ran fine when it was re-run, and I wasn't able to reproduce.

**Comment by JoeCreoterra** [comment]
@gafferongames whenever you have time I'd love to hear your thoughts on this PR. It looks like a great fix to get rid of having to send dummy reliable packets to avoid the issue, but was curious as to what you think.

**Comment by gafferongames** [comment]
I'm concerned around the heisenbug on tests. Please run locally on MacOS and loop the tests (while true). If it's an intermittent timing related test failure, then this approach usually catches it.

**Comment by gafferongames** [comment]
I believe this has been fixed in another PR. If I'm wrong, please let me know.

**Pull request closed without merging**
