### PR TITLE
Expose `GetClientUserData` on YojimboServer class. Fix address serialization bug in matcher code.

### PR DESCRIPTION
**Pull request by kbirk**
Hey there. I noticed there was no method exposed for that in `yojimbo` to access the userdata inside the connection token, so I added one.

I also noticed that my `userdata` bytes were "shifted" and including the trailing 12 bytes of the `ServerToClientKey` . After some debugging I realized that the `writeAddresses` function in the matcher code always increments the offset by 19, whether it is IPV4 or IPV6, but  `netcode` it reads only as many bytes as needed. So I fixed that too.

Cheers

### CODE REVIEW

**Comment by gafferongames** [comment]
Thanks! Can you please look into why macOS is not building?

**Comment by gafferongames** [comment]
I can take a look at it as well. It's curious, and doesn't seem to be triggered by your change?

**Comment by kbirk** [comment]
Yeah my change really shouldn't affect the CI. I'm wondering if it is because `macos-latest` uses apple silicon now: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners

Looks like that was it , I added  `libdirs { "/opt/homebrew/lib" }` to the premake file and that seems to have fixed it.

**Comment by gafferongames** [comment]
Bingo. Nice one

**Pull request merged**
